// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-k6Z3W3cYri5DpbUyoYjNtTmgaBTDW5w',
    appId: '1:354226270164:web:acff5860a007bfd41cf041',
    messagingSenderId: '354226270164',
    projectId: 'my-portfolio-8e114',
    authDomain: 'my-portfolio-8e114.firebaseapp.com',
    storageBucket: 'my-portfolio-8e114.appspot.com',
    measurementId: 'G-XDMTR0S8E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZDWN4p-1MWUuOKlTOMHnWvsUUpIP-YzQ',
    appId: '1:354226270164:android:02be33255c5396e01cf041',
    messagingSenderId: '354226270164',
    projectId: 'my-portfolio-8e114',
    storageBucket: 'my-portfolio-8e114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyRRZOsdzuP_eXMAccJmvNZ0HILXGLFpo',
    appId: '1:354226270164:ios:42522e8e1bf1c2bb1cf041',
    messagingSenderId: '354226270164',
    projectId: 'my-portfolio-8e114',
    storageBucket: 'my-portfolio-8e114.appspot.com',
    iosBundleId: 'com.example.myPortfolioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyRRZOsdzuP_eXMAccJmvNZ0HILXGLFpo',
    appId: '1:354226270164:ios:0e63c593609dea691cf041',
    messagingSenderId: '354226270164',
    projectId: 'my-portfolio-8e114',
    storageBucket: 'my-portfolio-8e114.appspot.com',
    iosBundleId: 'com.example.myPortfolioApp.RunnerTests',
  );
}
